import 'package:flutter/material.dart';

import 'app_colors.dart';

// ! If primary color was modified, make sure to change also the color -
// ! in flutter native splash & flutter launcher icon in pubspec.yml
final lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: AppColors.lightPrimary,
  onPrimary: const Color(0xFFFFFFFF),
  primaryContainer: const Color(0xFFffdbca),
  onPrimaryContainer: const Color(0xFF002019),
  secondary: const Color(0xFFdbc1ac),
  onSecondary: const Color(0xFFFFFFFF),
  secondaryContainer: const Color(0xFFCDE9DE),
  onSecondaryContainer: const Color(0xFF072019),
  tertiary: const Color(0xFFffffff),
  onTertiary: const Color(0xFFFFFFFF),
  tertiaryContainer: const Color(0xFFeae5ab),
  onTertiaryContainer: const Color(0xFF1e1c00),
  error: const Color(0xFFBA1A1A),
  errorContainer: const Color(0xFFFFDAD6),
  onError: const Color(0xFFFFFFFF),
  onErrorContainer: const Color(0xFF410002),
  background: const Color(0xFFFBFDFA),
  onBackground: const Color(0xFF191C1B),
  surface: const Color(0xFFFBFDFA),
  onSurface: const Color(0xFF191C1B),
  surfaceVariant: AppColors.greyColor,
  onSurfaceVariant: const Color(0xFF3F4945),
  outline: const Color(0xFF6F7975),
  onInverseSurface: const Color(0xFFEFF1EE),
  inverseSurface: const Color(0xFF362F2C),
  inversePrimary: const Color(0xFFFFB68F),
  shadow: const Color(0xFF000000),
  surfaceTint: const Color(0xFF974812),
  outlineVariant: const Color(0xFFBFC9C4),
  scrim: const Color(0xFF000000),
);

final darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: AppColors.darkPrimary,
  onPrimary: const Color(0xFFE4F7F3),
  primaryContainer: const Color(0xFF773200),
  onPrimaryContainer: const Color(0xFFFFDBCA),
  secondary: const Color(0xFFe6beab),
  onSecondary: const Color(0xFF432b1d),
  secondaryContainer: const Color(0xFF344C44),
  onSecondaryContainer: const Color(0xFFCDE9DE),
  tertiary: const Color(0xFFCEC991),
  onTertiary: const Color(0xFF343208),
  tertiaryContainer: const Color(0xFF4B481D),
  onTertiaryContainer: const Color(0xFFEAE5AB),
  error: const Color(0xFFFFB4AB),
  errorContainer: const Color(0xFF93000A),
  onError: const Color(0xFF690005),
  onErrorContainer: const Color(0xFFFFDAD6),
  background: const Color(0xFF191C1B),
  onBackground: const Color(0xFFE1E3E0),
  surface: const Color(0xFF191C1B),
  onSurface: const Color(0xFFE1E3E0),
  surfaceVariant: const Color(0xFF303234),
  onSurfaceVariant: const Color(0xFFBFC9C4),
  outline: const Color(0xFF89938E),
  onInverseSurface: const Color(0xFF191C1B),
  inverseSurface: const Color(0xFFECE0DB),
  inversePrimary: const Color(0xFF974812),
  shadow: const Color(0xFF000000),
  surfaceTint: const Color(0xFF222325),
  outlineVariant: const Color(0xFF3F4945),
  scrim: const Color(0xFF000000),
);


// from material builder
// const lightColorScheme = ColorScheme(
//   brightness: Brightness.light,
//   primary: Color(0xFF974812),
//   onPrimary: Color(0xFFFFFFFF),
//   primaryContainer: Color(0xFFFFDBCA),
//   onPrimaryContainer: Color(0xFF331200),
//   secondary: Color(0xFF765848),
//   onSecondary: Color(0xFFFFFFFF),
//   secondaryContainer: Color(0xFFFFDBCA),
//   onSecondaryContainer: Color(0xFF2B160A),
//   tertiary: Color(0xFF636032),
//   onTertiary: Color(0xFFFFFFFF),
//   tertiaryContainer: Color(0xFFEAE5AB),
//   onTertiaryContainer: Color(0xFF1E1C00),
//   error: Color(0xFFBA1A1A),
//   errorContainer: Color(0xFFFFDAD6),
//   onError: Color(0xFFFFFFFF),
//   onErrorContainer: Color(0xFF410002),
//   background: Color(0xFFFFFBFF),
//   onBackground: Color(0xFF201A17),
//   surface: Color(0xFFFFFBFF),
//   onSurface: Color(0xFF201A17),
//   surfaceVariant: Color(0xFFF4DED4),
//   onSurfaceVariant: Color(0xFF52443D),
//   outline: Color(0xFF85746B),
//   onInverseSurface: Color(0xFFFBEEE9),
//   inverseSurface: Color(0xFF362F2C),
//   inversePrimary: Color(0xFFFFB68F),
//   shadow: Color(0xFF000000),
//   surfaceTint: Color(0xFF974812),
//   outlineVariant: Color(0xFFD7C2B9),
//   scrim: Color(0xFF000000),
// );

// const darkColorScheme = ColorScheme(
//   brightness: Brightness.dark,
//   primary: Color(0xFFFFB68F),
//   onPrimary: Color(0xFF542100),
//   primaryContainer: Color(0xFF773200),
//   onPrimaryContainer: Color(0xFFFFDBCA),
//   secondary: Color(0xFFE6BEAB),
//   onSecondary: Color(0xFF432B1D),
//   secondaryContainer: Color(0xFF5C4132),
//   onSecondaryContainer: Color(0xFFFFDBCA),
//   tertiary: Color(0xFFCEC991),
//   onTertiary: Color(0xFF343208),
//   tertiaryContainer: Color(0xFF4B481D),
//   onTertiaryContainer: Color(0xFFEAE5AB),
//   error: Color(0xFFFFB4AB),
//   errorContainer: Color(0xFF93000A),
//   onError: Color(0xFF690005),
//   onErrorContainer: Color(0xFFFFDAD6),
//   background: Color(0xFF201A17),
//   onBackground: Color(0xFFECE0DB),
//   surface: Color(0xFF201A17),
//   onSurface: Color(0xFFECE0DB),
//   surfaceVariant: Color(0xFF52443D),
//   onSurfaceVariant: Color(0xFFD7C2B9),
//   outline: Color(0xFF9F8D84),
//   onInverseSurface: Color(0xFF201A17),
//   inverseSurface: Color(0xFFECE0DB),
//   inversePrimary: Color(0xFF974812),
//   shadow: Color(0xFF000000),
//   surfaceTint: Color(0xFFFFB68F),
//   outlineVariant: Color(0xFF52443D),
//   scrim: Color(0xFF000000),
// );
